### ISSUE TITLE
编译出dist后怎么用呢，需要另外搭建node服务来运行dist里的文件吗

### ISSUE THREAD

**Issue by jocongmin** [bodyno/universal-react-starter-kit#10]
编译出dist后怎么用呢，需要另外搭建node服务来运行dist里的文件吗，才能服务端渲染？

**Comment by bodyno** [comment]
放入nginx中即可

**Comment by jocongmin** [comment]
@bodyno 不可能吧，nginx是个服务而已，不能运行js吧？

**Comment by jocongmin** [comment]
对了，我说的是服务端渲染是怎么实现部署的

**Comment by bodyno** [comment]
需要在服务器上跑此node程序

**Comment by jocongmin** [comment]
怎么运行，直接node server.js 吗，还是要写一段node代码导入server.js 运行，或者你有没有案例

**Comment by bodyno** [comment]
`npm run start:prod`即可
